services:
  homebot:
    build: .
    container_name: jarvis_cerrado
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./src/jarvis/database:/app/src/jarvis/database
      - ./src/jarvis/storage:/app/src/jarvis/storage
      - ./.env:/app/.env
      - ./src/jarvis/config.yaml:/app/src/jarvis/config.yaml
    environment:
      - TZ=America/Sao_Paulo
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 2.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
